-- Migration: add short_label column to bjl_questions_v2
--
-- The April 2026 wave catalog tagger (scripts/tag_april_catalog.py) produces
-- a 5-10 word descriptor per question via Haiku 4.5. Existing schema didn't
-- have a column to store it. Adding short_label (nullable text) so the
-- April catalog inserts and any future tagger pass can persist the field.
--
-- Existing rows (questions 1-415) have short_label = NULL until they're
-- backfilled by a separate Haiku pass over the legacy catalog.

ALTER TABLE bjl_questions_v2
  ADD COLUMN IF NOT EXISTS short_label text;

COMMENT ON COLUMN bjl_questions_v2.short_label IS
  'Short 5-10 word descriptor of what the question measures. Generated by the catalog Haiku tagger; useful for investigator query summaries and the schema-doc surface.';
