-- ============================================================================
-- April 2026 wave catalog inserts
-- Auto-generated from data/april_inventory.json + tag outputs
-- ============================================================================

BEGIN;

-- Sanity check: verify current max IDs match expectations before inserting
DO $$
DECLARE
  current_max_q INT;
  current_max_i INT;
BEGIN
  SELECT COALESCE(MAX(question_id), 0) INTO current_max_q FROM bjl_questions_v2;
  SELECT COALESCE(MAX(item_id), 0) INTO current_max_i FROM bjl_items;
  IF current_max_q != 415 THEN
    RAISE EXCEPTION 'Expected max question_id=415, got %', current_max_q;
  END IF;
  IF current_max_i != 5391 THEN
    RAISE EXCEPTION 'Expected max item_id=5391, got %', current_max_i;
  END IF;
END $$;

-- ============================================================================
-- Insert 31 new questions
-- ============================================================================

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (416, 'Which of the following best describes your current banking situation? (Select one.)', 'financial_services', ARRAY['banking_relationship', 'account_consolidation', 'primary_bank_selection']::text[], 'single_select', 'Current banking situation and account structure');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (417, 'Which of the following types of financial institutions do you currently use? (Select all that apply.)', 'financial_services', ARRAY['financial_institution_types', 'banking_channels', 'neobank_adoption']::text[], 'multi_select', 'Types of financial institutions currently used');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (418, 'How long have you been with your primary bank or financial institution? (Select one.)', 'financial_services', ARRAY['banking_tenure', 'customer_longevity', 'relationship_duration']::text[], 'single_select', 'Length of relationship with primary bank');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (419, 'Think about the last time you opened a new bank account or seriously considered opening one. Which of the following best describes what triggered that moment? (Select up to 2.)', 'financial_services', ARRAY['account_opening_triggers', 'switching_motivations', 'life_changes']::text[], 'multi_select', 'Reasons for opening new bank accounts');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (420, 'When you discover a bank or financial institution that you feel genuinely good about, to what degree do each of the following bring you joy?', 'financial_services', ARRAY['banking_joy_drivers', 'emotional_satisfaction', 'trust_signals']::text[], 'joy_scale_0_to_5', 'Joy sources in banking relationships');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (421, 'When you are choosing a new bank or financial institution, how important is each of the following to you personally?', 'financial_services', ARRAY['bank_selection_criteria', 'feature_importance', 'decision_factors']::text[], 'importance_scale_0_to_5', 'Importance of bank selection factors');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (422, 'Thinking about the bank or financial institution you use most, to what degree does each of the following describe your relationship with it?', 'financial_services', ARRAY['banking_relationship_quality', 'trust_assessment', 'loyalty_drivers']::text[], 'description_scale_0_to_5', 'Satisfaction with primary banking relationship');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (423, 'Have you switched your primary bank or significantly changed your main banking relationship in the past three years?', 'financial_services', ARRAY['banking_switching_behavior', 'account_changes', 'primary_bank_retention']::text[], 'single_select', 'Bank switching and relationship changes');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (424, 'What was the most important reason you switched — or seriously considered switching — your primary banking relationship? (Select up to two.)', 'financial_services', ARRAY['switching_reasons', 'dissatisfaction_factors', 'competitive_alternatives']::text[], 'multi_select', 'Primary reasons for switching banks');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (425, 'What is the single most important thing your current bank does that keeps you from looking elsewhere? (Select one.)', 'financial_services', ARRAY['retention_drivers', 'switching_barriers', 'loyalty_factors']::text[], 'multi_select', 'Reasons for staying with current bank');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (426, 'When you think about your relationship with your primary bank or financial institution, which of the following types of joy, if any, does it bring you? (Select all that apply.)', 'financial_services', ARRAY['banking_emotional_benefits', 'psychological_satisfaction', 'joy_types']::text[], 'multi_select', 'Emotional joy from banking relationships');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (427, 'To what degree does each of the following describe your current relationship with money and financial institutions generally? Scale: 0 = Does not describe me at all, 5 = Describes me completely Rate each item', 'financial_services', ARRAY['financial_confidence', 'system_trust', 'money_attitudes']::text[], 'description_scale_0_to_5', 'General attitudes toward money and financial institutions');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (428, 'If your bank truly understood what your financial life feels like right now — the pressures, the goals, the moments of progress and setback — what would you most want it to do differently?', 'financial_services', ARRAY['banking_expectations', 'personalization_desires', 'customer_feedback']::text[], 'open_end', 'Desired improvements in banking experience');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (429, 'Which of the following best describes your relationship with wine? (Select one.)', 'food_beverage', ARRAY['wine_consumption_frequency', 'drinking_patterns', 'category_engagement']::text[], 'single_select', 'Wine drinking frequency and relationship');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (430, 'On which of these occasions do you tend to drink wine? (Select all that apply.)', 'food_beverage', ARRAY['wine_consumption_occasions', 'usage_contexts', 'drinking_situations']::text[], 'multi_select', 'Occasions for drinking wine');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (431, '(Select one.)', 'food_beverage', ARRAY['wine_consumption_trends', 'behavior_change', 'drinking_trajectory']::text[], 'single_select', 'Changes in wine consumption over time');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (432, 'You mentioned your wine drinking has decreased. Which of the following best describes why? (Select up to three.)', 'food_beverage', ARRAY['wine_drinking_decreased_reasons', 'consumption_barriers', 'category_resistance']::text[], 'multi_select', 'Reasons for decreased wine consumption');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (433, 'When you drink wine, to what degree do each of the following bring you joy?', 'food_beverage', ARRAY['wine_tasting_joy', 'sensory_pleasure', 'discovery_satisfaction']::text[], 'joy_scale_0_to_5', 'Joy sources from wine drinking');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (434, 'Still thinking about wine — which of the following joys, if any, does wine bring you? (Select all that apply.)', 'food_beverage', ARRAY['wine_emotional_benefits', 'joy_types', 'psychological_satisfaction']::text[], 'multi_select', 'Types of joy wine brings to life');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (435, 'When you are choosing what to drink to relax, celebrate, or enjoy socially, to what degree does each of the following bring you joy?', 'food_beverage', ARRAY['beverage_choice_joy', 'drink_selection', 'relaxation_beverages']::text[], 'joy_scale_0_to_5', 'Joy from choosing different beverages');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (436, 'When you choose what to drink for an evening, how important is each of the following to you?', 'food_beverage', ARRAY['beverage_selection_criteria', 'decision_importance', 'purchase_factors']::text[], 'importance_scale_0_to_5', 'Importance of drink selection factors');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (437, 'Which of the following, if any, describe why you tend to choose something other than wine, or why wine is not a bigger part of your life? (Select all that apply.)', 'food_beverage', ARRAY['wine_category_barriers', 'consumption_obstacles', 'preference_drivers']::text[], 'multi_select', 'Reasons for choosing alternatives to wine');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (438, 'Is there anything that, if it were true about wine, would make you more interested in drinking it or drinking it more often?', 'food_beverage', ARRAY['wine_category_improvement', 'consumption_incentives', 'category_evolution']::text[], 'open_end', 'Factors that would increase wine consumption');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (439, 'Thinking about wine specifically — to what degree does each of the following describe your experience of the wine category?', 'food_beverage', ARRAY['wine_category_perception', 'accessibility_beliefs', 'gatekeeping_concerns']::text[], 'description_scale_0_to_5', 'Perceptions of wine as a category');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (440, 'Thinking about the wine you have most enjoyed — or the wine experience that has most stayed with you — what made it memorable? ', 'food_beverage', ARRAY['memorable_wine_experiences', 'emotional_resonance', 'experience_narratives']::text[], 'open_end', 'Memorable wine experiences and moments');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (441, 'When you think about how wine fits into your life and identity, which of the following feels most true for you? (Select up to two.)', 'food_beverage', ARRAY['wine_identity_role', 'category_relevance', 'lifestyle_alignment']::text[], 'multi_select', 'Wine''s role in personal identity');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (442, 'How much do you agree with each of the following statements about the direction wine is heading as a category?', 'food_beverage', ARRAY['wine_category_outlook', 'industry_trends', 'generational_relevance']::text[], 'multi_select', 'Beliefs about wine category direction');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (443, 'In what price range are the BOTTLES of wine you most frequently purchase at STORES?', 'food_beverage', ARRAY['wine_price_sensitivity', 'retail_spending', 'purchase_price_point']::text[], 'mixed', 'Wine bottle price range preferences');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (444, 'In what price range are the GLASSES of wine you most frequently purchase at bars or restaurants?', 'food_beverage', ARRAY['wine_on_premise_pricing', 'restaurant_spending', 'glass_price_point']::text[], 'mixed', 'Wine glass price range at on-premise venues');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (445, 'We have asked you about two very different topics — banking and wine. Looking across both, which of the following comes closest to how you feel about traditional, established categories like these? (Select one.)', 'financial_services', ARRAY['legacy_vs_challenger', 'consumer_attitudes', 'banking', 'wine']::text[], 'single_select', 'Legacy versus challenger brand preference across categories');

INSERT INTO bjl_questions_v2 (question_id, question_text, primary_topic, subtags, question_type, short_label) VALUES
  (446, 'Thinking across all the categories and brands that are part of your life — from banking to food and drink to entertainment — which of the following types of joy do you most want the things you choose to bring you? (Select your top three.)', 'general_joy', ARRAY['joy_type_priorities', 'life_satisfaction_drivers', 'emotional_benefits']::text[], 'multi_select', 'Top joy types desired across all categories');


-- ============================================================================
-- Insert ~199 new items (linked to questions above)
-- ============================================================================

INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5392, 416, '(single-item) Which of the following best describes your current banking situation? (Select on', 'financial_services', ARRAY['banking_situation', 'account_status']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5393, 417, 'A national bank (such as Chase, Bank of America, or Wells Fargo)', 'financial_services', ARRAY['institution_type', 'national_bank']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5394, 417, 'A regional or community bank', 'financial_services', ARRAY['institution_type', 'regional_community_bank']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5395, 417, 'A credit union', 'financial_services', ARRAY['institution_type', 'credit_union']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5396, 417, 'An online-only bank (such as Ally, Marcus, or Discover)', 'financial_services', ARRAY['institution_type', 'online_bank']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5397, 417, 'A neobank or fintech app (such as Chime, SoFi, Cash App, or Venmo)', 'financial_services', ARRAY['institution_type', 'neobank_fintech']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5398, 417, 'A brokerage with banking features (such as Fidelity or Charles Schwab)', 'financial_services', ARRAY['institution_type', 'brokerage_banking']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5399, 417, 'None — I do not currently have a bank account', 'financial_services', ARRAY['institution_type', 'no_account']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5400, 418, '(single-item) How long have you been with your primary bank or financial institution? (Select ', 'financial_services', ARRAY['tenure_duration', 'primary_bank']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5401, 419, 'I found a better interest rate or financial return elsewhere', 'financial_services', ARRAY['account_opening_motivation', 'interest_rates']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5402, 419, 'I was offered a sign-up bonus, promotion, or cash incentive', 'financial_services', ARRAY['account_opening_motivation', 'sign_up_bonus']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5403, 419, 'Someone I trust recommended an institution to me', 'financial_services', ARRAY['account_opening_motivation', 'recommendation_trust']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5404, 419, 'I had a frustrating or disappointing experience with my current bank', 'financial_services', ARRAY['account_opening_motivation', 'dissatisfaction_switch']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5405, 419, 'I was going through a life change such as a new job, a move, or a major purchase', 'financial_services', ARRAY['account_opening_motivation', 'life_change']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5406, 419, 'I saw advertising or content online or on social media', 'financial_services', ARRAY['account_opening_motivation', 'advertising_social_media']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5407, 419, 'I was looking for a specific feature or tool my current bank did not offer', 'financial_services', ARRAY['account_opening_motivation', 'feature_seeking']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5408, 419, 'My financial situation changed and I needed something different', 'financial_services', ARRAY['account_opening_motivation', 'financial_situation_change']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5409, 419, 'I have not opened a new account or considered doing so recently', 'financial_services', ARRAY['account_opening_motivation', 'no_recent_action']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5410, 419, 'Other - Write In', 'financial_services', ARRAY['account_opening_motivation', 'other_writein']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5411, 419, 'Other - Write In (col 103)', 'financial_services', ARRAY['account_opening_motivation', 'other_writein']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5412, 420, 'Feeling like it was built for people like me', 'financial_services', ARRAY['emotional_drivers', 'brand_alignment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5413, 420, 'Knowing exactly what I will and will not be charged', 'financial_services', ARRAY['emotional_drivers', 'fee_transparency']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5414, 420, 'A recommendation from someone whose financial judgment I trust', 'financial_services', ARRAY['emotional_drivers', 'social_recommendation']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5415, 420, 'Seeing that other people my age use it and feel good about it', 'financial_services', ARRAY['emotional_drivers', 'peer_adoption']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5416, 420, 'Having tools or features that help me understand my own finances better', 'financial_services', ARRAY['emotional_drivers', 'financial_literacy_tools']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5417, 420, 'The feeling that this institution actually wants me to succeed financially', 'financial_services', ARRAY['emotional_drivers', 'financial_success_partner']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5418, 420, 'Feeling like I am getting a genuinely good deal', 'financial_services', ARRAY['emotional_drivers', 'value_proposition']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5419, 420, 'Knowing my money is safe and protected', 'financial_services', ARRAY['emotional_drivers', 'safety_security']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5420, 420, 'Being able to manage everything from my phone without visiting a branch', 'financial_services', ARRAY['emotional_drivers', 'mobile_convenience']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5421, 420, 'Feeling welcomed and respected rather than evaluated or judged', 'financial_services', ARRAY['emotional_drivers', 'respect_inclusion']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5422, 421, 'High interest rates on savings', 'financial_services', ARRAY['selection_criteria', 'interest_rates']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5423, 421, 'Low or no fees', 'financial_services', ARRAY['selection_criteria', 'fees']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5424, 421, 'A good mobile app experience', 'financial_services', ARRAY['selection_criteria', 'mobile_app']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5425, 421, 'The ability to speak to a real person when I need to', 'financial_services', ARRAY['selection_criteria', 'customer_service']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5426, 421, 'Physical branch locations near me', 'financial_services', ARRAY['selection_criteria', 'physical_branches']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5427, 421, 'A company that shares my values', 'financial_services', ARRAY['selection_criteria', 'values_alignment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5428, 421, 'A strong reputation and long track record', 'financial_services', ARRAY['selection_criteria', 'reputation_track_record']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5429, 421, 'Speed and ease of getting started', 'financial_services', ARRAY['selection_criteria', 'onboarding_ease']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5430, 421, 'Transparency about how they make money', 'financial_services', ARRAY['selection_criteria', 'business_model_transparency']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5431, 421, 'Tools that help me budget, save, or track spending', 'financial_services', ARRAY['selection_criteria', 'financial_tools']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5432, 421, 'A brand that feels modern and relevant to my life', 'financial_services', ARRAY['brand_perception', 'modern_relevance', 'bank_selection']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5433, 422, 'I feel like they treat me as an individual, not just an account number', 'financial_services', ARRAY['personal_treatment', 'customer_relationship', 'individualization']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5434, 422, 'I trust them to be upfront about fees and any changes to my account', 'financial_services', ARRAY['fee_transparency', 'trust', 'institutional_honesty']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5435, 422, 'I feel like they are genuinely invested in my financial wellbeing', 'financial_services', ARRAY['financial_wellbeing', 'genuine_care', 'customer_investment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5436, 422, 'I would recommend them to a close friend without hesitation', 'financial_services', ARRAY['brand_trust', 'recommendation', 'loyalty']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5437, 422, 'I feel some loyalty to them even when I see better offers elsewhere', 'financial_services', ARRAY['loyalty', 'competitive_offers', 'switching_behavior']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5438, 422, 'Managing my finances through them brings me a sense of confidence', 'financial_services', ARRAY['confidence', 'financial_management', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5439, 422, 'They make me feel capable and in control of my financial life', 'financial_services', ARRAY['control', 'capability', 'empowerment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5440, 422, 'I feel like they understand the financial realities people my age face', 'financial_services', ARRAY['generational_understanding', 'relatable', 'age_relevant']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5441, 422, 'I have thought about leaving them in the past year', 'financial_services', ARRAY['switching_consideration', 'loyalty_risk', 'retention']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5442, 422, 'I feel proud to be a customer of theirs', 'financial_services', ARRAY['brand_pride', 'customer_satisfaction', 'emotional_connection']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5443, 423, '(single-item) Have you switched your primary bank or significantly changed your main banking r', 'financial_services', ARRAY['switching_behavior', 'banking_relationship', 'none_option']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5444, 424, 'I was charged unexpected or unfair fees', 'financial_services', ARRAY['unexpected_fees', 'switching_reason', 'cost']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5445, 424, 'I had a poor customer service experience', 'financial_services', ARRAY['customer_service', 'switching_reason', 'service_quality']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5446, 424, 'I found significantly better interest rates elsewhere', 'financial_services', ARRAY['interest_rates', 'switching_reason', 'competitive_advantage']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5447, 424, 'I found an institution that felt more modern or more suited to my lifestyle', 'financial_services', ARRAY['modern_institution', 'switching_reason', 'lifestyle_fit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5448, 424, 'I felt like my bank did not value me as a customer', 'financial_services', ARRAY['customer_value', 'switching_reason', 'recognition']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5449, 424, 'I needed features or services my bank did not offer', 'financial_services', ARRAY['features', 'services', 'switching_reason']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5450, 424, 'My financial situation changed and my needs evolved', 'financial_services', ARRAY['financial_evolution', 'life_circumstances', 'switching_reason']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5451, 424, 'I went through a major life change such as moving, a new job, or a new relationship', 'financial_services', ARRAY['major_life_change', 'switching_reason', 'relocation']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5452, 424, 'A recommendation from someone I trust', 'financial_services', ARRAY['word_of_mouth', 'recommendation', 'switching_reason']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5453, 424, 'Other - Write In', 'financial_services', ARRAY['open_response', 'switching_reason', 'other']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5454, 424, 'Other - Write In (col 146)', 'financial_services', ARRAY['open_response', 'switching_reason', 'other']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5455, 425, '(single-item) What is the single most important thing your current bank does that keeps you fr', 'financial_services', ARRAY['retention_factor', 'banking_relationship', 'none_option']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5456, 425, 'Other - Write In', 'financial_services', ARRAY['open_response', 'retention_factor', 'other']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5457, 426, 'A sense of freedom — feeling financially unencumbered and in control of my choices', 'financial_services', ARRAY['freedom', 'financial_control', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5458, 426, 'A sense of achievement — feeling capable, competent, and on top of my finances', 'financial_services', ARRAY['achievement', 'competence', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5459, 426, 'A sense of connection — feeling genuinely understood and cared for', 'financial_services', ARRAY['connection', 'understanding', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5460, 426, 'A sense of peace — feeling secure, stable, and protected', 'financial_services', ARRAY['peace', 'security', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5461, 426, 'A sense of inspiration — feeling motivated and energized about my financial future', 'financial_services', ARRAY['inspiration', 'motivation', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5462, 426, 'A sense of pride — feeling like I am making smart, responsible choices', 'financial_services', ARRAY['pride', 'responsibility', 'emotional_benefit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5463, 426, 'Honestly, my bank does not bring me any particular kind of joy', 'general_joy', ARRAY['joy_absence', 'banking_relationship', 'no_emotional_connection']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5464, 426, 'I have never thought about my bank in terms of joy before', 'general_joy', ARRAY['joy_awareness', 'banking_relationship', 'no_prior_reflection']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5465, 427, 'I feel confident about where my finances are headed', 'financial_services', ARRAY['financial_confidence', 'future_outlook', 'personal_assessment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5466, 427, 'I feel like the financial system is designed to work for people like me', 'financial_services', ARRAY['system_fairness', 'financial_inclusion', 'institutional_trust']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5467, 427, 'I feel like my bank genuinely understands the financial realities of my life', 'financial_services', ARRAY['bank_understanding', 'financial_realities', 'empathy']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5468, 427, 'Managing my finances brings me more stress than joy', 'financial_services', ARRAY['financial_stress', 'money_management', 'emotional_impact']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5469, 427, 'I feel like I have the tools and knowledge I need to make good financial decisions', 'financial_services', ARRAY['financial_capability', 'knowledge', 'competence']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5470, 427, 'I feel like achieving real financial security is within reach for me', 'financial_services', ARRAY['financial_security', 'achievability', 'aspirational']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5471, 427, 'I often feel behind financially compared to where I thought I would be at this stage of life', 'financial_services', ARRAY['financial_lag', 'comparison', 'personal_anxiety']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5472, 427, 'I believe a great banking relationship could genuinely change someone''s financial trajectory', 'financial_services', ARRAY['banking_relationship', 'financial_trajectory', 'trust_institutions']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5473, 428, '(single-item) If your bank truly understood what your financial life feels like right now — th', 'financial_services', ARRAY['banking_relationship', 'emotional_understanding']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5474, 429, '(single-item) Which of the following best describes your relationship with wine? (Select one.)', 'food_beverage', ARRAY['wine_relationship', 'wine_preference']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5475, 430, 'A relaxed evening at home, winding down', 'food_beverage', ARRAY['wine_occasions', 'home_relaxation', 'wind_down']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5476, 430, 'Dinner at home with family or a partner', 'food_beverage', ARRAY['wine_occasions', 'family_dining', 'home_meal']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5477, 430, 'Dinner at a restaurant', 'food_beverage', ARRAY['wine_occasions', 'restaurant_dining']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5478, 430, 'A social gathering or party', 'food_beverage', ARRAY['wine_occasions', 'social_gathering', 'party']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5479, 430, 'A special occasion or celebration', 'food_beverage', ARRAY['wine_occasions', 'celebration', 'special_occasion']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5480, 430, 'Outdoors — a picnic, a concert, or a casual outdoor setting', 'food_beverage', ARRAY['wine_occasions', 'outdoor_settings', 'picnic']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5481, 430, 'A tasting, winery visit, or wine-focused event', 'food_beverage', ARRAY['wine_occasions', 'tasting_events', 'winery_visit']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5482, 430, 'Pairing with a specific food I am cooking or eating', 'food_beverage', ARRAY['wine_occasions', 'food_pairing', 'cooking']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5483, 430, 'With no particular occasion — just when I feel like it', 'food_beverage', ARRAY['wine_occasions', 'casual_drinking']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5484, 430, 'Other - Write In', 'food_beverage', ARRAY['wine_occasions', 'open_ended']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5485, 430, 'Other - Write In (col 179)', 'food_beverage', ARRAY['wine_occasions', 'open_ended']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5486, 431, 'In the past year, would you say your wine drinking has', 'food_beverage', ARRAY['wine_consumption_trend', 'drinking_habits']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5487, 432, 'I am trying to drink less alcohol overall', 'food_beverage', ARRAY['wine_decrease_reason', 'alcohol_reduction', 'health_conscious']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5488, 432, 'I gave up alcohol entirely', 'food_beverage', ARRAY['wine_decrease_reason', 'sobriety', 'alcohol_abstinence']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5489, 432, 'I have found non-alcoholic drinks I genuinely enjoy', 'food_beverage', ARRAY['wine_decrease_reason', 'non_alcoholic_drinks', 'substitution']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5490, 432, 'I have been drinking other alcoholic beverages more', 'food_beverage', ARRAY['wine_decrease_reason', 'other_beverages', 'substitution']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5491, 432, 'Wine feels too expensive for what I get', 'food_beverage', ARRAY['wine_decrease_reason', 'price_sensitivity', 'value_perception']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5492, 432, 'I am more health-conscious than I used to be', 'food_beverage', ARRAY['wine_decrease_reason', 'health_consciousness']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5493, 432, 'My social occasions have changed and wine fits less naturally', 'food_beverage', ARRAY['wine_decrease_reason', 'lifestyle_change', 'social_occasions']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5494, 432, 'I never felt fully confident choosing wine and it got tiring', 'food_beverage', ARRAY['wine_decrease_reason', 'choice_anxiety', 'confidence']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5495, 432, 'Other - Write In', 'food_beverage', ARRAY['wine_decrease_reason', 'open_ended']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5496, 432, 'Other - Write In (col 190)', 'food_beverage', ARRAY['wine_decrease_reason', 'open_ended']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5497, 433, 'The pleasure of a glass that tastes exactly right in the moment', 'food_beverage', ARRAY['taste_pleasure', 'sensory_enjoyment', 'wine_satisfaction']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5498, 433, 'The feeling of discovering a wine you love that you had never tried before', 'food_beverage', ARRAY['discovery', 'wine_exploration', 'novelty']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5499, 433, 'Sharing a bottle with people you care about', 'food_beverage', ARRAY['social_sharing', 'wine_togetherness', 'connection']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5500, 433, 'Learning something new about wine, a region, or how it is made', 'food_beverage', ARRAY['learning', 'wine_education', 'knowledge_building']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5501, 433, 'The way a good wine makes an ordinary meal feel special', 'food_beverage', ARRAY['elevation', 'meal_enhancement', 'special_moments']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5502, 433, 'Being someone who appreciates beautiful, well-crafted things', 'food_beverage', ARRAY['craftsmanship_appreciation', 'quality_value', 'identity']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5503, 433, 'Connecting with a place, a culture, or a story through what is in the glass', 'food_beverage', ARRAY['cultural_connection', 'place_story', 'wine_terroir']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5504, 433, 'The ritual of opening a bottle — the ceremony and the anticipation', 'food_beverage', ARRAY['ritual_ceremony', 'anticipation', 'wine_opening']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5505, 433, 'Finding a wine that is excellent at a surprisingly good price', 'food_beverage', ARRAY['value_discovery', 'price_quality', 'deal_finding']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5506, 433, 'The feeling that wine slows things down and invites you to be present', 'food_beverage', ARRAY['mindfulness', 'presence', 'slowing_down']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5507, 433, 'Sharing your wine knowledge with others', 'food_beverage', ARRAY['knowledge_sharing', 'expertise', 'social_role']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5508, 433, 'Being a wine expert among your social circle', 'food_beverage', ARRAY['expertise', 'authority', 'social_status']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5509, 434, 'Playful — it is fun, lighthearted, and unpretentious', 'food_beverage', ARRAY['playfulness', 'fun', 'lighthearted', 'unpretentious']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5510, 434, 'Aesthetic — it is beautiful, sensory, and carefully crafted', 'food_beverage', ARRAY['aesthetic_beauty', 'sensory_craft', 'design_appreciation']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5511, 434, 'Hedonic — pure sensory pleasure in the moment', 'food_beverage', ARRAY['hedonism', 'sensory_pleasure', 'immediate_gratification']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5512, 434, 'Sentimental — it connects me to memories, people, or places', 'food_beverage', ARRAY['wine_joy', 'sentimental_connection', 'memory_nostalgia']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5513, 434, 'Relational — it brings me closer to the people I share it with', 'food_beverage', ARRAY['wine_joy', 'social_connection', 'relational']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5514, 434, 'Achievement — I feel capable and knowledgeable when I choose well', 'food_beverage', ARRAY['wine_joy', 'achievement', 'competence']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5515, 434, 'Freedom — it represents leisure, indulgence, and time that is mine', 'food_beverage', ARRAY['wine_joy', 'freedom', 'indulgence']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5516, 434, 'Awe — certain wines genuinely amaze me with their complexity or quality', 'food_beverage', ARRAY['wine_joy', 'awe', 'amazement']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5517, 434, 'Inspiration — wine makes me curious and motivated to learn and discover more', 'food_beverage', ARRAY['wine_joy', 'inspiration', 'curiosity']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5518, 434, 'Wine does not bring me any particular type of joy', 'food_beverage', ARRAY['wine_joy', 'no_joy', 'neutral']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5519, 435, 'Wine', 'food_beverage', ARRAY['wine', 'beverage_choice', 'relaxation_celebration']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5520, 435, 'Craft or specialty beer', 'food_beverage', ARRAY['beer', 'craft_beer', 'beverage_choice']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5521, 435, 'Cocktails or mixed drinks', 'food_beverage', ARRAY['cocktails', 'mixed_drinks', 'beverage_choice']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5522, 435, 'Spirits — whiskey, tequila, gin, etc. — on their own', 'food_beverage', ARRAY['spirits', 'liquor', 'beverage_choice']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5523, 435, 'Hard seltzers or canned cocktails', 'food_beverage', ARRAY['hard_seltzer', 'canned_cocktails', 'beverage_choice']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5524, 435, 'Non-alcoholic beer or wine', 'food_beverage', ARRAY['non_alcoholic', 'beer_alternative', 'wine_alternative']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5525, 435, 'Sparkling water or botanical drinks such as Seedlip or Ghia', 'food_beverage', ARRAY['sparkling_water', 'botanical_drinks', 'non_alcoholic']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5526, 435, 'A non-alcoholic cocktail or mocktail', 'food_beverage', ARRAY['mocktail', 'non_alcoholic', 'cocktail_alternative']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5527, 435, 'Cannabis or other legal alternatives', 'food_beverage', ARRAY['cannabis', 'legal_alternatives', 'beverage_choice']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5528, 435, 'Beer', 'food_beverage', ARRAY['beer', 'beverage_choice', 'relaxation_celebration']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5529, 436, 'Knowing what is in it and how it was made', 'food_beverage', ARRAY['ingredient_transparency', 'production_knowledge', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5530, 436, 'It being produced sustainably or responsibly', 'food_beverage', ARRAY['sustainability', 'responsible_production', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5531, 436, 'It having a compelling story or origin', 'food_beverage', ARRAY['brand_story', 'origin_narrative', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5532, 436, 'It feeling appropriate for who I am and how I live', 'food_beverage', ARRAY['identity_alignment', 'lifestyle_fit', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5533, 436, 'It being something I can talk about or share with friends', 'food_beverage', ARRAY['social_shareability', 'conversation_starter', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5534, 436, 'The overall experience it creates, beyond just the taste', 'food_beverage', ARRAY['overall_experience', 'occasion_fit', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5535, 436, 'How it makes me feel — the mood it puts me in', 'food_beverage', ARRAY['mood', 'emotional_impact', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5536, 436, 'Low or no alcohol content', 'food_beverage', ARRAY['low_alcohol', 'health_conscious', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5537, 436, 'Value for the price', 'food_beverage', ARRAY['price_value', 'affordability', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5538, 436, 'How easy it is to choose with confidence', 'food_beverage', ARRAY['ease_of_choice', 'confidence', 'beverage_criteria']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5539, 437, 'I find wine intimidating or hard to choose with confidence', 'food_beverage', ARRAY['wine_intimidation', 'choice_difficulty', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5540, 437, 'I do not drink alcohol.', 'food_beverage', ARRAY['non_drinker', 'alcohol_abstinence', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5541, 437, 'I prefer the taste of other drinks', 'food_beverage', ARRAY['taste_preference', 'flavor_profile', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5542, 437, 'I am trying to reduce my alcohol consumption overall', 'food_beverage', ARRAY['alcohol_reduction', 'health_conscious', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5543, 437, 'Wine can feel like it is for a certain type of person and I do not always feel that is me', 'food_beverage', ARRAY['social_perception', 'identity_fit', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5544, 437, 'Wine feels expensive relative to other options I enjoy', 'food_beverage', ARRAY['price_barrier', 'cost_perception', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5545, 437, 'I do not always know what to expect from a wine before I buy it', 'food_beverage', ARRAY['quality_unpredictability', 'purchase_uncertainty', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5546, 437, 'I have found non-alcoholic options I genuinely enjoy', 'food_beverage', ARRAY['non_alcoholic_alternatives', 'product_satisfaction', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5547, 437, 'Other beverages feel more fun or social in the settings I am in', 'food_beverage', ARRAY['social_context', 'occasion_fit', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5548, 437, 'I associate wine with older generations more than my own', 'food_beverage', ARRAY['age_perception', 'generational_association', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5549, 437, 'Health concerns specifically related to wine', 'health_wellness', ARRAY['health_concern', 'wine_specific', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5550, 437, 'Other - Write In', 'food_beverage', ARRAY['open_ended', 'other_reason', 'wine_barriers']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5551, 437, 'None of these — wine is already a significant part of my life', 'food_beverage', ARRAY['wine_consumption', 'established_habit', 'wine_engagement']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5552, 437, 'Other - Write In (col 246)', 'food_beverage', ARRAY['wine_preferences', 'open_ended_response']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5553, 438, '(single-item) Is there anything that, if it were true about wine, would make you more interest', 'food_beverage', ARRAY['wine_interest', 'no_response']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5554, 439, 'Wine feels like it was made for people like me', 'food_beverage', ARRAY['wine_identity', 'personal_relevance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5555, 439, 'Choosing wine confidently feels out of reach without expert knowledge', 'food_beverage', ARRAY['wine_knowledge', 'confidence_barrier']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5556, 439, 'Wine has a culture of gatekeeping that can feel unwelcoming', 'food_beverage', ARRAY['wine_culture', 'gatekeeping', 'inclusivity']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5557, 439, 'I think of wine as something that gets better the more you learn about it', 'food_beverage', ARRAY['wine_learning', 'expertise']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5558, 439, 'Wine feels like a category that is genuinely evolving and becoming more relevant', 'food_beverage', ARRAY['wine_category', 'evolution', 'relevance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5559, 439, 'The wine industry speaks to me and people like me', 'food_beverage', ARRAY['wine_industry', 'resonance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5560, 439, 'Wine is a category I would like to explore more if it was easier to start exploring', 'food_beverage', ARRAY['wine_exploration', 'accessibility']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5561, 439, 'Non-alcoholic wine options are something I would genuinely consider', 'food_beverage', ARRAY['wine_nonalcoholic', 'alternatives']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5562, 439, 'The challenge of choosing a wine is a big part of the joy of wine', 'food_beverage', ARRAY['wine_choice', 'challenge', 'enjoyment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5563, 440, '(single-item) Thinking about the wine you have most enjoyed — or the wine experience that has ', 'food_beverage', ARRAY['wine_experience', 'no_response']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5564, 441, 'Wine is a genuine passion — it is a significant part of who I am', 'food_beverage', ARRAY['wine_identity', 'passion', 'central_role']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5565, 441, 'Wine is something I enjoy when the occasion calls for it, but it is not central to my identity', 'food_beverage', ARRAY['wine_identity', 'occasional_use']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5566, 441, 'Wine is something I am curious about and would like to explore more', 'food_beverage', ARRAY['wine_identity', 'curiosity', 'exploration']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5567, 441, 'Wine is something I tolerate or go along with in social situations', 'food_beverage', ARRAY['wine_identity', 'social_tolerance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5568, 441, 'Wine feels like it belongs to a different generation or lifestyle than mine', 'food_beverage', ARRAY['wine_identity', 'generational', 'lifestyle']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5569, 441, 'Wine is something I have consciously moved away from', 'food_beverage', ARRAY['wine_identity', 'deliberate_avoidance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5570, 441, 'Wine is simply not something I think about much', 'food_beverage', ARRAY['wine_identity', 'neutral_stance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5571, 442, 'Wine is becoming more accessible and welcoming to new drinkers', 'food_beverage', ARRAY['wine_category_direction', 'accessibility', 'inclusivity']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5572, 442, 'Wine is losing relevance with younger generations', 'food_beverage', ARRAY['wine_category_direction', 'generational_relevance']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5573, 442, 'The growth of non-alcoholic wine options is making the category more interesting', 'food_beverage', ARRAY['wine_category_direction', 'nonalcoholic_wine']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5574, 442, 'Wine has a story and a craft that other beverages cannot match', 'food_beverage', ARRAY['wine_category_direction', 'craft', 'heritage']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5575, 442, 'Social media and apps have made choosing wine less intimidating', 'food_beverage', ARRAY['wine_category_direction', 'technology', 'apps']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5576, 442, 'Wine culture still needs to do more to feel genuinely inclusive', 'food_beverage', ARRAY['wine_category_direction', 'inclusivity', 'culture']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5577, 442, 'I believe wine can be for everyone, regardless of age, background, or expertise', 'food_beverage', ARRAY['wine_category_direction', 'accessibility', 'inclusivity']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5578, 443, '(single-item) In what price range are the BOTTLES of wine you most frequently purchase at STOR', 'food_beverage', ARRAY['wine_purchase', 'price_range']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5579, 444, '(single-item) In what price range are the GLASSES of wine you most frequently purchase at bars', 'food_beverage', ARRAY['wine_purchase', 'price_range', 'on_premise']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5580, 445, '(single-item) We have asked you about two very different topics — banking and wine. Looking ac', 'financial_services', ARRAY['legacy_vs_challenger', 'consumer_attitudes']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5581, 446, 'Playful joy — fun, lighthearted, and spontaneous', 'general_joy', ARRAY['playful', 'fun', 'lighthearted', 'spontaneous']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5582, 446, 'Aesthetic joy — beautiful, thoughtfully crafted, and sensory', 'general_joy', ARRAY['aesthetic', 'beautiful', 'crafted', 'sensory']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5583, 446, 'Hedonic joy — pure pleasure in the moment', 'general_joy', ARRAY['hedonic', 'pleasure', 'moment']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5584, 446, 'Relational joy — connecting me more deeply with people I care about', 'general_joy', ARRAY['relational', 'connection', 'people']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5585, 446, 'Achievement joy — making me feel capable, knowledgeable, and in control', 'general_joy', ARRAY['achievement', 'capability', 'knowledge', 'control']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5586, 446, 'Freedom joy — giving me a feeling of independence and open possibility', 'general_joy', ARRAY['freedom', 'independence', 'possibility']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5587, 446, 'Awe — occasionally stopping me in my tracks with something extraordinary', 'general_joy', ARRAY['awe', 'extraordinary']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5588, 446, 'Inspirational joy — sparking my curiosity and motivating me to learn and grow', 'general_joy', ARRAY['inspirational', 'curiosity', 'learning', 'growth']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5589, 446, 'Sentimental joy — connecting me to memories, people, and the past', 'general_joy', ARRAY['sentimental', 'memories', 'nostalgia', 'connection']::text[], false, NULL);
INSERT INTO bjl_items (item_id, question_id, item_name, primary_topic, subtags, is_brand, canonical_brand) VALUES (5590, 446, 'Self-actualization joy — aligning with my deepest values and sense of purpose', 'general_joy', ARRAY['self_actualization', 'values', 'purpose']::text[], false, NULL);

COMMIT;

-- Verification queries (run after commit):
-- SELECT COUNT(*) FROM bjl_questions_v2;       -- expect 446
-- SELECT COUNT(*) FROM bjl_items;              -- expect ~5590
-- SELECT MAX(question_id), MAX(item_id) FROM bjl_questions_v2 q JOIN bjl_items i ON i.question_id = q.question_id;